name: Deploy Reset Leaderboard Function

on:
  schedule:
    - cron: '0 16 * * 0'  # Every Sunday at midnight AWST (UTC+8)
  workflow_dispatch: # allows manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-amd64 > supabase
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

      - name: Deploy Edge Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: nlgiukcwbexfxkzdvzzq
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase functions deploy reset_leaderboard
